# Generated by Django 2.2.3 on 2019-07-02 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copybook',
            name='edition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
