# Generated by Django 2.2.3 on 2019-07-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190702_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbook',
            name='date_devolution',
            field=models.DateField(blank=True, null=True),
        ),
    ]
